import { Kanit } from 'next/font/google';
// import { Nunito } from 'next/font/google';
import "./globals.css";
import NavBar from '@/components/NavBar';
import BottomBar from '@/components/BottomBar';

const kanit = Kanit({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})
// const nunito = Nunito({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${kanit.className} antialiased bg-[#041316] `}
      >
        <div className="min-h-screen text-white">
          <NavBar />
          <main className="pt-4 pb-16 sm:pt-20 sm:pb-0">{children}</main>
          <BottomBar />
        </div>
        {/* {children} */}
      </body>
    </html>
  );
}
